### ISSUE TITLE
Fitzpatrick modifier isn’t working correctly with latest version of emoji-db

### ISSUE THREAD

**Issue by meyer** [meyer/emoji-db#2]
![screenshot 2017-10-15 13 04 17](https://user-images.githubusercontent.com/13781/31588602-6a6e2b8a-b1a9-11e7-9da4-1fcbbbbc8884.png)

**Comment by Geczy** [comment]
I don't understand, what's happening now, and what's the expected outcome?

**Comment by meyer** [comment]
@Geczy the skin tone modifier (🏾, or `U+1F3FE`) is being incorrectly applied to the preceding emoji, which makes the resulting emoji show as two separate entities, 👩‍🌾 and 🏾, instead of the desired single emoji:

![woman_farmer 4](https://user-images.githubusercontent.com/13781/42423883-14ffb83c-82b7-11e8-93af-e68ff073e792.png)

**Comment by meyer** [comment]
basically the way i’m combining emoji and modifiers is incorrect and i need to re-read the spec to figure out the right way.

**Comment by meyer** [comment]
fixed in master

![Screenshot 2019-12-31 03 39 00](https://user-images.githubusercontent.com/13781/71615392-1b795980-2b7f-11ea-924d-75afa715bcfe.png)
