### ISSUE TITLE
Missing 🙇‍♀️

### ISSUE THREAD

**Issue by Geczy** [meyer/emoji-db#3]
🙇‍♀️ is not in the emoji json 

https://emojipedia.org/woman-bowing-deeply/

**Comment by meyer** [comment]
@Geczy ah yeah, that’s a Fitzpatrick modifier issue (see #2). There’s an entry for “person bowing” but it only contains the non-fitz version (which in this case is “man bowing deeply” 🙇). I’ll take a look this weekend.

**Comment by meyer** [comment]
confirmed fixed in master

![Screenshot 2019-12-31 03 35 22](https://user-images.githubusercontent.com/13781/71615294-968e4000-2b7e-11ea-976d-2734d492fce1.png)
