### ISSUE TITLE
rake error - No such file or directory @ rb_sysopen - /emoji-db-master/cache/unicode-annotations.xml

### ISSUE THREAD

**Issue by Jianan-Li** [meyer/emoji-db#4]
Sorry I don't have any experience with ruby or rake. I'm trying to run it myself, but encountered this error. Could you shed some light on how I can fix this? Thank you!

<img width="466" alt="screen shot 2019-02-16 at 11 31 17 am" src="https://user-images.githubusercontent.com/3374769/52902437-b8890900-31de-11e9-999a-cdba6b847063.png">

**Comment by meyer** [comment]
@Jianan-Li thanks for the report! The issue has been fixed in latest master.
